### ISSUE TITLE
Pipeline of releasing website fails

### ISSUE THREAD

**Issue by pkosiec** [kyma-project/website#98]
Presumably it is related to used token during content generation. The problem is that I've already generated a new token and it still fails.

```
09:38:05 Status: Downloaded newer image for eu.gcr.io/kyma-project/documentation-generator:0.1.49
09:38:06 
09:38:06 > documentation-builder@0.1.0 start /app
09:38:06 > node src/index.js
09:38:06 
09:38:08 Reading current configuration from /app/documentation/config.json
09:38:08 Checking releases for kyma-project/kyma
09:38:08 { HttpError: {"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
09:38:08     at response.text.then.message (/app/node_modules/@octokit/rest/lib/request/request.js:72:19)
09:38:08     at process._tickCallback (internal/process/next_tick.js:68:7)
09:38:08   name: 'HttpError',
09:38:08   code: 401,
09:38:08   status: undefined,
09:38:08   headers:
09:38:08    { 'access-control-allow-origin': '*',
09:38:08      'access-control-expose-headers':
09:38:08       'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
09:38:08      connection: 'close',
09:38:08      'content-length': '83',
09:38:08      'content-security-policy': 'default-src \'none\'',
09:38:08      'content-type': 'application/json; charset=utf-8',
09:38:08      date: 'Tue, 30 Oct 2018 08:38:08 GMT',
09:38:08      'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
09:38:08      server: 'GitHub.com',
09:38:08      status: '401 Unauthorized',
09:38:08      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
09:38:08      'x-content-type-options': 'nosniff',
09:38:08      'x-frame-options': 'deny',
09:38:08      'x-github-media-type': 'github.v3; format=json',
09:38:08      'x-github-request-id': 'C720:4CFC:6FDA80:D8D8A0:5BD8186F',
09:38:08      'x-ratelimit-limit': '60',
09:38:08      'x-ratelimit-remaining': '59',
09:38:08      'x-ratelimit-reset': '1540892288',
09:38:08      'x-xss-protection': '1; mode=block' } }
09:38:08 npm ERR! code ELIFECYCLE
09:38:08 npm ERR! errno 1
09:38:08 npm ERR! documentation-builder@0.1.0 start: `node src/index.js`
09:38:08 npm ERR! Exit status 1
09:38:08 npm ERR! 
09:38:08 npm ERR! Failed at the documentation-builder@0.1.0 start script.
09:38:08 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
09:38:09 
09:38:09 npm ERR! A complete log of this run can be found in:
09:38:09 npm ERR!     /root/.npm/_logs/2018-10-30T08_38_08_161Z-debug.log
09:38:11 ✗ Failed
```

**Comment by pkosiec** [comment]
I've regenerated token, updated secrets and now it works fine.
